server:
  port: 8081
spring:
  sql:
    init:
      mode: embedded
  jpa:
    show-sql: true
    format-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${db_url}
    username: ${db_user_name}
    password: ${db_password}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    type: com.zaxxer.hikari.HikariDataSource
    pool-size: 1
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 1
  mvc:
    servelet:
      path: /api

java:
  naming:
    factory:
      initial: com.sun.enterprise.naming.SerialInitContextFactory

management:
  endpoints:
    web:
      exposure:
        include: health, ping
    health:
      group:
        custom:
          include: health, ping
